# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'formula-ios' do
  pod "PromiseKit", "~> 3.0"
  pod "SwiftForms"
end

target 'formula-iosTests' do

end

target 'formula-iosUITests' do

end
